* Einfuehrung
** Mensch
  
   A human has a sensory input buffer.
   Short term memory.
   Long term memory.
  
  Constantly we're blasted with sensory input.
 There is way more sensory data than we can store in our brain.

 This sensory buffer can be seen as the CPU registers, it holds very little information but is extremely fast. which later gets transfered to our short term memory (CPU cache).

** Gesetz der Naehe

 Aufzug mit Schalter daneben, mann nimmt an das diesert Schalter fuer den Aufzug ist aber
 est ist eigentlich der Lichtschalter.

** Gesetz der Aehnlichkeit

** Gesetz der guten Fortsetzung

 Zebras, tarnen sich in der Gruppe weil die Muster sich zusammen blenden.
 Dadurch erscheinen sie groesser.

** Gesetz der Geschlossenheit

** Gesetz der Bewegung

 Fliegen die sich als Gruppe bewegen.

** Mustererkennung

 Buch lesen, speedreading, oft wird beim normalen lesen zuruck geguckt fuer fehlende Information.
 Aber wenn man einfach weiterlesen wurde wurde sich die Information aus dem Kontext deutlich machen.

** Fitt's Gesetz (46/77) 1710
  
   Notausschalter bei der Saege oder aehnliches.
  
   Gewichtete Sortierung: Task menu nach Benutzungshauefigkeit sortieren.
  
   
   
* Klausurrelevant

** Individuelle Unterschiede
   
*** Dauerhaft
**** Geschlecht
**** Physische Eigenschaften
**** Intelligenz
**** Kultur
*** Temporaer
**** Stress
**** Muedigkeit
*** Flexibel
**** Alter
     
* Nicht in Klausur

** Slide 66-69/77

Deduktiv, induktives und abduktives Argumentieren
